// SEGUNDA VERTENTE (UPA/SUS) por conduta — gerado por workflow clinico (autor + revisor de UPA/SUS),
// verificado quanto a realismo (REMUME) e seguranca. Apoio a decisao; conferir protocolo local.

export const UPA: Record<string, string[]> = {
  "sri": [
    "DROGAS QUE A UPA TEM (substitua o ideal pelo da REMUME). Indutor: sem etomidato, use CETAMINA 1,5-2 mg/kg IV (1ª escolha em choque/sepse/broncoespasmo - preserva PA; 50 mg/mL). Alternativa SO em normotenso: MIDAZOLAM 0,1-0,3 mg/kg (indutor fraco/lento e derruba PA - nao use no instavel). Bloqueador: sem rocuronio, use SUCCINILCOLINA 1-1,5 mg/kg IV (CONTRAINDICADA em hipercalemia/IRC dialitica, queimadura ou esmagamento >48h, lesao medular/AVC antigo, doenca neuromuscular, rabdomiolise, hipertermia maligna). REGRA DE OURO: se vai intubar de verdade, NUNCA sede sem bloquear - sedacao isolada = aspiracao e via aerea perdida.",
    "OTIMIZE A FISIOLOGIA ANTES ('resuscitate before you intubate'): trate hipotensao (cristaloide; se nao corrige, NORADRENALINA em BIC se houver, ou push-dose de adrenalina como ponte - diluir 1 mL de 1 mg/mL em 9 mL SF = 100 mcg/mL e aplicar 0,5-2 mL [50-200 mcg] cada 1-5 min; rotular a seringa, dose certa = nao matar). Corrija hipoglicemia. Isso evita a PCR peri-intubacao, que e a real causa de morte no procedimento.",
    "PRE-OXIGENE com o que existe: 3-5 min com mascara com reservatorio a 15 L/min OU VNI/CPAP se a SatO2 nao sobe. Mantenha CATETER NASAL a 15 L/min DURANTE a laringoscopia (oxigenacao apneica - compra os segundos que faltam sem videolaringoscopio). Posicao orelha-esterno, cabeceira 25-30 graus; em obeso/gestante faca rampa com lencois.",
    "PLANO DE VIA AEREA DIFICIL pronto ANTES de sedar: AMBU + Guedel + mascara testados, bougie (ou fio-guia/sonda firme como introdutor), lamina extra e MASCARA LARINGEA/supraglotico como resgate imediato. MAXIMO 2-3 tentativas e, ENTRE ELAS, VENTILE com AMBU+Guedel ate recuperar SatO2. 'Nao intuba, nao ventila' = plano D: CRICOTIREOIDOSTOMIA (kit proprio ou tecnica cirurgica com bisturi + bougie + tubo 6.0).",
    "SEM CAPNOGRAFIA (realidade da UPA), confirme por MULTIPLOS sinais: visao direta do tubo passando as cordas, ausculta de 5 pontos (EPIGASTRIO PRIMEIRO), embacamento do tubo, expansao toracica simetrica e SatO2 estavel/subindo. Use detector colorimetrico (EtCO2 descartavel) se houver. NA DUVIDA, RETIRE O TUBO E VENTILE - intubacao esofagica nao reconhecida mata. Marque a profundidade (22-23 cm no homem, ~21 cm na mulher na rima labial) e fixe bem. Pos-IOT: sedacao+analgesia continua (midazolam + fentanil/morfina, ou cetamina em BIC), cabeceira elevada, sonda gastrica, monitor continuo; reavalie o tubo a cada transferencia de maca.",
    "ACIONE A REGULACAO JA, EM PARALELO (nao depois): ligue para a Central de Regulacao/SAMU assim que o caso ultrapassar a UPA (precisa UTI, hemodinamica, neuro, dialise ou cirurgia). Transfira INTUBADO e ESTAVEL, em ambulancia de SUPORTE AVANCADO, com VAGA CONFIRMADA, medico/enfermeiro acompanhante e drogas de sedacao para o trajeto. Documente vitais, glicemia, ECG, condutas e horarios. Em caso tempo-dependente (IAM, AVC, sepse, trauma) NAO espere 'melhorar sozinho'."
  ],
  "cardioversao": [
    "INSTABILIDADE = NAO ESPERE: havendo sinal de gravidade (PAS<90/hipotensao, dor toracica isquemica, dispneia/congestao, rebaixamento), a cardioversao eletrica e mandatoria mesmo SEM o sedativo ideal. Todo desfibrilador de UPA tem SYNC: aperte SYNC, CONFIRME as marcas sobre cada QRS e use bifasico (FA 120-200J, flutter/TSV 50-100J, TV monomorfica com pulso 100J, escalonando). EXCECAO: TV polimorfica/torsades NAO sincroniza de forma confiavel - se instavel, trate como FV e DESFIBRILE (choque NAO sincronizado).",
    "SEDACAO COM O QUE TEM (cetamina e a melhor opcao no instavel): Sem etomidato/propofol, prefira Cetamina 0,5-1 mg/kg IV (item da REMUME, mantem a PA - ideal no hipotenso). Alternativa: Midazolam 0,05-0,1 mg/kg IV em bolus tituladas (1-3 mg) +/- Fentanil 1 mcg/kg, vigiando hipotensao e depressao respiratoria. Deixe Flumazenil/Naloxona a beira-leito SO como resgate (nunca de rotina/profilatico). Principio: nao se adia um choque que salva vida por falta do sedativo perfeito - se o paciente estiver muito instavel, choque com a melhor sedacao/amnesia possivel no momento; nunca deixe de sedar quando ha qualquer condicao de faze-lo.",
    "SE NAO HA DESFIBRILADOR/SYNC FUNCIONANTE - PONTE FARMACOLOGICA, ULTIMO RECURSO enquanto regula transferencia: FA/flutter sem instabilidade franca, controle de FC com Metoprolol 5 mg IV lento (repetir ate 15 mg) ou Diltiazem - CONTRAINDICADOS em IC descompensada e em FA pre-excitada/WPW (QRS largo irregular); TSV (QRS estreito regular) Manobra Vagal + Adenosina 6 mg IV em bolus rapido com flush, repetir 12 mg; TV monomorfica estavel Amiodarona 150 mg em 10 min. Na INSTABILIDADE VERDADEIRA o choque e superior - droga e so ponte e nunca substitui o choque no paciente grave.",
    "OXIGENIO, MONITOR E ACESSO sempre antes de sedar: O2 para SpO2>=94%, monitor multiparametrico (ECG continuo, oximetria, PA nao-invasiva a cada 3-5 min), 2 acessos venosos calibrosos, via aerea e carrinho de parada AO LADO. Corrija o corrigivel: K+, Mg+ (MgSO4 1-2 g IV se TV/torsades ou suspeita de disturbio - item da REMUME) e glicemia capilar.",
    "ACIONE REGULACAO/SAMU 192 PRECOCE, EM PARALELO (nao depois): ao identificar instabilidade ou arritmia que pode recorrer, solicite vaga em UTI/cardiologia. Documente ritmo (foto/ECG de 12 derivacoes), drogas, doses e horarios. Transfira SEMPRE apos retorno ao ritmo sinusal/estabilizacao, com monitor e desfibrilador no transporte e medico/enfermeiro acompanhando.",
    "ANTICOAGULACAO E SEGURANCA NA CARDIOVERSAO ELETIVA: so adie o choque se o paciente estiver ESTAVEL. Em FA >48h ou tempo indeterminado SEM instabilidade, NAO cardioverta sem anticoagulacao/avaliacao de trombo (risco de AVC): controle a FC, inicie anticoagulante disponivel (Enoxaparina SC, REMUME) e regule para servico com ECO transesofagico. Na instabilidade hemodinamica real, o beneficio do choque supera o risco e ele NAO deve ser adiado."
  ],
  "acls-pcr": [
    "RCP de alta qualidade nao depende de insumo caro: compressoes continuas 100-120/min, 5-6 cm, retorno total do torax, minimo de interrupcoes (<10 s), rodizio do compressor a cada 2 min. Sem tabua de RCP, use o chao ou a maca rigida. Sem capnografia (padrao-ouro de qualidade): cheque RITMO e PULSO central SO na pausa a cada 2 min (nao interrompa compressoes para 'sentir pulso' no meio do ciclo); melhora de cor/esforco respiratorio sao apenas indicios. O melhor item que voce tem e o monitor-desfibrilador/DEA: ligue e use ASSIM que chegar.",
    "Adrenalina 1 mg (1:1.000, ampola 1 mL) IV/IO a cada 3-5 min e UNIVERSAL na REMUME - quase sempre disponivel; precoce no ritmo NAO chocavel. Sem acesso venoso periferico rapido em veia calibrosa: puncao INTRAOSSEA (tibia proximal/umero) e o plano B padrao e seguro - toda UPA deveria ter agulha/dispositivo de IO. Sem IO: persista no acesso periferico calibroso (nao atrase a droga). Apos cada bolus, flush de 20 mL de SF e eleve o membro. NAO faca adrenalina intracardiaca nem doses 'altas' de rotina.",
    "FV/TV sem pulso: DESFIBRILAR (nao sincronizado) e a prioridade - choque sempre que indicado, antes de focar na droga. Sem amiodarona (frequente faltar na UPA): LIDOCAINA 1-1,5 mg/kg IV/IO, repetir 0,5-0,75 mg/kg a cada 5-10 min ate o teto de 3 mg/kg - alternativa consagrada do ACLS e quase sempre estocada. Em TV polimorfica/QT longo (torsades) ou suspeita de hipomagnesemia: SULFATO DE MAGNESIO 1-2 g IV em 1-2 min.",
    "Trate as causas reversiveis (Hs/Ts) com o que existe na UPA: HIPOVOLEMIA - SF 0,9% em bolus rapido (sem hemocomponente, expanda e regule vaga de hemotransfusao); HIPOXIA - via aerea: se nao intubar, mascara com reservatorio + ventilacao com BVM (AMBU) bem feita salva tanto quanto o tubo; HIPERCALEMIA suspeita (renal cronico/dialitico) - GLUCONATO DE CALCIO 10% 10-20 mL IV (protege a membrana) + glicoinsulina (10 UI de insulina regular IV + 50 mL de glicose 50%) +/- bicarbonato de sodio 8,4% (em via separada); HIPOGLICEMIA - glicose 50%; opioide - NALOXONA se disponivel. PNEUMOTORAX hipertensivo - puncao de alivio com jelco 14G no 2o EIC linha hemiclavicular OU 5o EIC linha axilar media.",
    "Defina cedo o teto e o destino: se ROSC, estabilize (SatO2-alvo 92-98%, evite hiperoxia e hiperventilacao; PAS >=90 com SF +/- noradrenalina se houver; ECG 12 derivacoes buscando IAM/SCA) e ACIONE A REGULACAO (Complexo Regulador/SAMU) IMEDIATAMENTE - pos-ROSC e prioridade vermelha para vaga em terciario. IAM com SST sem hemodinamica/transferencia em tempo: TROMBOLISE conforme protocolo SO se RCP nao foi prolongada nem traumatica e sem outra contraindicacao (RCP prolongada e fator de risco de sangramento). Transporte sempre monitorizado, com acesso, adrenalina disponivel e via aerea garantida, equipe acompanhando.",
    "Decisao e registro: PCR refrataria, sem causa reversivel, apos RCP adequada e prolongada - considere suspender com criterio clinico/etico, comunicando a familia; nao prolongue futilidade nem transfira PCR ativa instavel sem ROSC. Documente horarios, ritmos, drogas, numero de choques e ROSC. Antes de qualquer transferencia, fale com a regulacao com dados objetivos (ritmo inicial, tempo de PCR, ROSC, vasoativas em uso) para garantir a vaga."
  ],
  "iot": [
    "SEDOANALGESIA SEM BOMBA (cenario mais comum na UPA): sem bomba de infusao, faca midazolam + fentanil em bolus intermitente sob demanda (ex.: midazolam 2-3mg + fentanil 25-50mcg EV a cada 15-30min) titulando para RASS -3/-4 com a MENOR dose eficaz. Bolus se acumulam: cheque PA e FR apos cada dose (risco de hipotensao/apneia). Se so houver midazolam, associe morfina 2-4mg EV. Mantenha SEMPRE analgesia junto da sedacao (paciente curarizado ou sedado raso = dor/sofrimento oculto). Deixe 1 frasco de cada ja diluido, rotulado e a beira-leito.",
    "SEM PROPOFOL/DEXMEDETOMIDINA: use o que existe na REMUME — midazolam + fentanil (1a linha real). Cetamina 0,5-1mg/kg EV em bolus (manutencao 0,25-0,5mg/kg a cada 10-15min, ou BIC em dose baixa se houver bomba) e otima na UPA: sedacao + analgesia, preserva PA e drive ventilatorio — util no broncoespasmo e no hipotenso. Evite bloqueador neuromuscular CONTINUO; se houver assincronia, APROFUNDE a sedacao/analgesia primeiro e so curarize (rocuronio/succinilcolina) em bolus pontual — NUNCA com paciente acordado ou sub-sedado.",
    "CONFIRMACAO E VENTILACAO COM RECURSO LIMITADO: confirme o tubo por ausculta (5 pontos) + condensacao + expansao simetrica + SpO2 estavel; capnografia (curva/EtCO2) e o padrao-ouro. Detector colorimetrico de CO2 so CONFIRMA posicao inicial (e pode falhar em PCR/baixo fluxo) — NAO monitora ventilacao continua nem substitui capnografia. Sem ventilador de transporte: AMBU + valvula PEEP em O2 alto, FR 10-12, volume que eleva so o torax (sem hiperinsuflar). No ventilador disponivel use modo simples (VCV/PCV), VC 6mL/kg de PESO PREDITO (calculado por altura/sexo, nao peso real), PEEP 5, FiO2 titulada para SpO2 >=92-94% (evite hiperoxia mantida).",
    "MONITORIZACAO E SEGURANCA MINIMA: oximetria + PA (automatica a cada 5-10min se disponivel) + cardioscopia continuas. Cabeceira 30-45 graus (anti-broncoaspiracao/PAV), tubo bem fixado e com a ALTURA marcada (cm na rima), SNG/SOG para descomprimir o estomago. Aspirador funcionante e material de via aerea (laringo + bougie + tubo reserva do mesmo numero e um abaixo) ao lado para extubacao acidental. Cheque glicemia, sinais de dor/agitacao e reavalie a sedacao a cada bolus.",
    "ESTABILIZAR ANTES DE TRANSPORTAR (regra do 'paciente travado'): so libere ambulancia/vaga com SpO2, PA e FC estaveis, sedoanalgesia garantida para todo o trajeto e drogas suficientes para o tempo de transporte + dobro (leve ampolas extras de midazolam, fentanil, cetamina e SF, alem do material de via aerea). Trate hipotensao ANTES de sair: SF 250-500mL e, se refrataria, noradrenalina diluida em acesso confiavel; como resgate de bolus use metaraminol (comum na UPA) ou push-dose de noradrenalina/fenilefrina diluida. NUNCA transporte paciente hipoxico ou hipotenso instavel.",
    "ACIONAR REGULACAO/SAMU IMEDIATAMENTE apos a IOT: classifique como VAGA ZERO / urgencia (paciente em ventilacao mecanica nao entra em fila). Solicite UTI movel / USA com ventilador e profissional habilitado; passe SBAR objetivo (idade, causa da IOT, parametros atuais, drogas em uso, peso). Registre o nome do regulador e o horario. Se a vaga demorar, mantenha sedado/ventilado, reavalie de hora em hora e escale a regulacao/coordenacao/ouvidoria — documente tudo no prontuario."
  ],
  "bradi-instavel": [
    "ATROPINA é a 1ª linha e quase sempre tem na UPA: 1 mg IV em bolus, repetir a cada 3-5 min até 3 mg no total. Sem acesso venoso rápido? Use a via INTRAÓSSEA (EZ-IO ou agulha de IO na tubérosidade tibial) com a mesma dose. Atenção: em BAV 2º grau Mobitz II e BAVT (sobretudo com QRS largo / escape ventricular) a atropina costuma falhar e pode até piorar — não perca tempo, já prepare cronotrópico em BIC e/ou marca-passo. Dose mínima é 1 mg (doses <0,5 mg causam bradicardia paradoxal).",
    "Marca-passo: se houver MARCA-PASSO TRANSCUTÂNEO (muitos cardioversores/monitores da UPA têm o modo pacing nas pás/eletrodos), use-o como ponte enquanto a droga não age ou se ela falhar — coloque sedação/analgesia (ex.: fentanil/midazolam em dose baixa, com cautela na hipotensão) porque o estímulo é doloroso, e confirme CAPTURA elétrica E mecânica (pulso/PA, não só o spike na tela). Se a UPA não tiver pacing, o substituto real é droga em gotejamento; o soco precordial rítmico (~60/min) serve só por segundos como contingência, não conte com ele.",
    "VASOATIVO em infusão contínua — preferir BIC; na falta, microgotas no equipo com vigilância dedicada. ADRENALINA (ampola 1 mg/1 mL, item da REMUME): 1 mg em 250 mL de SF 0,9% (=4 mcg/mL), correr 2-10 mcg/min (≈30-150 mL/h), titulando por FC/PA. DOPAMINA, se disponível: 5-20 mcg/kg/min. Sem bomba, alguém deve ficar SÓ vigiando o gotejo, reavaliando FC/PA a cada 2-3 min, idealmente em veia calibrosa (risco de necrose por extravasamento de vasopressor em veia periférica fina).",
    "Trate a CAUSA reversível já na UPA — é o que mais resolve sem tecnologia. ECG de 12 derivações + glicemia capilar SEMPRE. HIPERCALEMIA (IRC/diálise, T apiculada, QRS alargado) → gluconato de cálcio 10% 10-20 mL IV lento + glicoinsulina (10 UI regular em 50 mL de glicose 50%). INTOXICAÇÃO por betabloqueador/BCC → cálcio, glucagon se houver, insulina em altas doses se protocolo disponível. DIGITÁLICO, HIPÓXIA, HIPOTERMIA e IAM de parede inferior (atenção ao VD — pode precisar de volume) também causam bradicardia instável.",
    "ACIONE A REGULAÇÃO/SAMU EM PARALELO, não depois — ligue assim que a bradicardia for instável (rebaixamento, dor torácica, hipotensão, congestão/choque), pois marca-passo transvenoso definitivo, hemodinâmica e UTI só existem no terciário. Já deixe documentados FC, ritmo (com o ECG impresso), PA, drogas em uso e horários para a transferência e para o cardiologista regulador.",
    "TRANSFIRA com segurança: paciente monitorizado (cardioscopia + oximetria + PA), acesso venoso/IO pérvio, vasoativo já diluído e correndo, e pás de marca-passo coladas no tórax como contingência se houver risco de parada no trajeto. Solicite ambulância de SUPORTE AVANÇADO (USA) com médico; se a regulação só dispuser de suporte básico e o paciente estiver instável, mantenha a estabilização e reavalie o transporte com o regulador — não despache instável em viatura sem médico/desfibrilador."
  ],
  "taqui-algoritmo": [
    "INSTAVEL (hipotensao/dor toracica/dispneia/rebaixamento/congestao) = CARDIOVERSAO JA, nao espere droga ideal nem transferencia. Quase toda UPA tem desfibrilador/monitor: pegue veia, monitorize, O2 se SatO2<94%. Sede se der tempo e PA permitir: midazolam 1-2mg IV +/- fentanil 25-50mcg; se hipotenso, cetamina 0,5mg/kg IV - mas NUNCA deixe de cardioverter o paciente em colapso por falta de sedativo. Choque SINCRONIZADO (ligar SYNC e reconferir antes de cada choque): QRS estreito regular/flutter 50-100J, FA 120-150J, QRS largo monomorfico 100J, escalonando. Sem pulso, FV ou TV polimorfica instavel = desfibrilacao NAO-sincronizada (200J bifasico/maximo do aparelho) + RCP.",
    "ESTAVEL QRS ESTREITO REGULAR (TPSV): manobra vagal PRIMEIRO - custo zero, sempre disponivel (Valsalva modificada: sopra seringa de 10mL sentado/semideitado, depois deita e eleva as pernas 15s). Se houver adenosina: 6mg IV em bolus MUITO rapido em veia calibrosa antecubital + flush imediato de 20mL e elevar o braco; repetir 12mg. Adenosina e barata mas falta com frequencia: alternativa = verapamil 2,5-5mg IV lento (2-3min) OU metoprolol 5mg IV lento - SOMENTE com PA boa e QRS comprovadamente estreito SEM pre-excitacao; nenhum dos dois esta garantido na UPA. Falhou tudo ou nao tem droga = cardioversao eletiva sincronizada 50-100J sob sedacao (sempre disponivel e segura).",
    "ESTAVEL FA/FLUTTER com alta resposta: o foco e CONTROLE DE FREQUENCIA, NAO reverter o ritmo (risco embolico se inicio >48h ou incerto - so reverte FA aguda <48h ou ja anticoagulado/sem trombo). Controle de FC mais realista na UPA: metoprolol 5mg IV lento, repetir ate 15mg, OU betabloqueador VO (propranolol/metoprolol/atenolol - sempre na REMUME). Se IC descompensada/disfuncao de VE conhecida: prefira digoxina (0,25-0,5mg IV ou VO) e EVITE betabloqueador/verapamil. NUNCA associe betabloqueador + verapamil/diltiazem (risco de BAV/assistolia). FA irregular com QRS largo e bizarro = suspeite WPW: NAO use bloqueador do no AV (adenosina/verapamil/diltiazem/digoxina/betabloqueador) - so amiodarona ou cardioversao.",
    "ESTAVEL QRS LARGO: trate como TV ate prova em contrario. Carro-chefe = amiodarona 150mg IV diluida em 100mL SF/SG em 10min (NUNCA bolus rapido - hipotensao), pode repetir, depois manutencao ~1mg/min - amiodarona e item amplamente disponivel na REMUME/UPA. Torsades/QT longo ou suspeita de hipomagnesemia (alcoolista/diuretico/vomitos): sulfato de magnesio 1-2g IV em 10-15min (barato e quase sempre disponivel) - e NAO use amiodarona no torsades. Corrija K+ e Mg+: colha eletrolitos (gasometria/point-of-care se houver) e na duvida reponha magnesio empiricamente.",
    "ESTABILIZE e ja REGULE EM PARALELO (nao depois): acione a Central de Regulacao/CROSS desde o inicio do atendimento. Transferir para hospital com hemodinamica/UTI: TV sustentada, FA/flutter que nao controla, isquemia/IAM associado, instabilidade recorrente ou pos-cardioversao, indicacao de anticoagulacao/ablacao. Antes e durante o transporte: 2 acessos venosos, monitor + desfibrilador na ambulancia, pas de marcapasso/cardioversao prontas, droga em curso identificada na bomba/equipo, ECG impresso e resumo do caso. Paciente instavel NAO vai em USB (basica): exige USA/SAMU avancada com medico ou equipe habilitada.",
    "ARMADILHAS E SEGURANCA (realidade UPA): SEMPRE ECG de 12 derivacoes antes e depois - separa TPSV de flutter 2:1 (FC ~150) e TV de TSV com aberrancia, e isso muda a droga; na duvida QRS largo = TV. Adenosina causa pausa/rubor assustadores que duram segundos: avise o paciente, deixe o monitor gravando (a pausa revela ondas de flutter e ajuda no diagnostico) e tenha desfibrilador ao lado. Cardioversao eletiva em FA de inicio incerto so apos avaliar risco embolico. Em gestante: cardioversao e segura e adenosina e 1a linha na TPSV. Documente ritmo, drogas, energias e horarios - subnotificacao e problema medico-legal."
  ],
  "choque-sepse": [
    "ATB amplo JA com o que existe na REMUME: na falta de pip-tazo/meropenem (raros em UPA), iniciar ceftriaxona 2 g IV. Some metronidazol 500 mg IV no foco abdominal/pelvico e ciprofloxacino 400 mg IV no foco urinario. Se quiser reforcar Gram-negativo, ASSOCIE amicacina 15 mg/kg/dia (ou gentamicina 5-7 mg/kg/dia) ao beta-lactamico - NUNCA aminoglicosideo isolado (nao cobre Gram-positivo nem anaerobio). Colete 2 hemoculturas se houver frasco, mas NUNCA atrase a 1a dose por exame, hemocultura ou transferencia.",
    "Ressuscitar com Ringer lactato (preferir) ou SF 0,9% ate ~30 mL/kg, em bolus de 500 mL com REAVALIACAO a cada bolus (ausculta pulmonar, perfusao, diurese, FR). Sem bomba: macrogotas totalmente aberto, pressurizador manual ou bracadeira de PA inflada (~300 mmHg) sobre a bolsa. Em idoso/cardiopata/renal fracione e reavalie congestao a cada etapa - nao infunda 30 mL/kg no automatico.",
    "Vasopressor se PAM <65 apos volume: noradrenalina e a 1a escolha (16 mg/250 mL SG5% = 64 mcg/mL; iniciar 0,05-0,1 mcg/kg/min, titular ate PAM >=65). Idealmente em BIC e acesso central; sem central, NA periferica e aceitavel por tempo curto em VEIA CALIBROSA E PROXIMAL (antecubital), bem fixada, com vigilancia continua de extravasamento. Se extravasar: parar a infusao na hora, aspirar pelo cateter, elevar o membro e trocar de acesso (fentolamina, antidoto classico, em geral NAO existe na UPA). Sem BIC, gravidade/microgotas so como ponte de emergencia com calculo conferido e dupla checagem. Dopamina apenas se nao houver nada melhor (mais arritmia).",
    "Monitorizar a resposta sem lactato laboratorial por marcadores clinicos SERIADOS: PAM, diurese (sondar, meta >0,5 mL/kg/h), nivel de consciencia, enchimento capilar, FR e SatO2; use lactato/gasometria point-of-care se houver. Reavalie a cada 15-30 min na fase aguda, buscando tanto hipoperfusao persistente quanto sinais de congestao por excesso de volume.",
    "ACIONAR REGULACAO/SAMU JA, EM PARALELO a estabilizacao (nao depois): todo choque septico precisa de leito de UTI/terciario. Antes de remover garanta: 2 acessos venosos, via aerea avaliada (O2; IOT se rebaixado/falencia), vasopressor titulado e estavel, glicemia corrigida e ATB ja infundido. Transfira acompanhado por medico/enfermeiro, com bomba (ou plano de infusao manual) e material de via aerea de backup.",
    "Controle de foco e suporte que cabem na UPA: O2 para SatO2 >=94%, antitermico, controle glicemico, drenar/remover foco obvio e ja acessivel (sonda obstruida, abscesso superficial). Se for intubar antes do transporte, lembre que IOT no choque septico tem alto risco de parada peri-intubacao: otimize volume/PA antes, prefira cetamina como indutor e deixe vasopressor correndo/pronto."
  ],
  "iam-supra": [
    "REPERFUSAO E TEMPO: confirme STEMI por supra de ST em >=2 derivacoes contiguas (ou BRE/BRD novo) e ACIONE A REGULACAO/SAMU JA, em PARALELO. Se a ICP nao for alcancavel em ate 120 min do primeiro contato, FACA TROMBOLISE na UPA (ate 12h de dor, idealmente <30min porta-agulha) salvo contraindicacao. CHECKLIST DE CONTRAINDICACAO ABSOLUTA antes de lisar: AVC hemorragico previo/AVC isquemico <6m, sangramento ativo, trauma/cirurgia/TCE recentes, dissecao de aorta, neoplasia/MAV intracraniana. Tenecteplase (TNK, peso-dependente, metade da dose se >=75a) e a meta da REMUME; se so houver alteplase, use bolus 15mg + 0,75mg/kg (max 50) em 30min + 0,5mg/kg (max 35) em 60min; estreptoquinase 1,5 mi UI em 30-60min so se for o unico disponivel (cuidado hipotensao - reduza/pause o gotejo). Marque os horarios (dor, porta, agulha).",
    "ANTIAGREGACAO + ANTICOAGULACAO compativel com a REMUME: AAS 150-300mg macerado/mastigado SEMPRE (salvo alergia). Clopidogrel associado a trombolise: ataque 300mg se <75 anos; SEM ataque (75mg) se >=75 anos. Anticoagulante e OBRIGATORIO junto da fibrinolise: enoxaparina (se <75a: bolus 30mg EV + 1mg/kg SC 12/12h; se >=75a: SEM bolus, 0,75mg/kg SC 12/12h; ajuste/troque por HNF se ClCr<30) OU HNF EV (bolus 60 UI/kg, max 4000, + infusao 12 UI/kg/h). NAO use ticagrelor/prasugrel com fibrinolitico.",
    "MONITORIZACAO E ARRITMIA DA 1a HORA: paciente em monitor + desfibrilador a beira-leito + 2 acessos venosos + O2 SO se SatO2<90%. FV/TV sem pulso = desfibrilacao IMEDIATA (nao sincronizada) + RCP/ACLS. Bradicardia/BAVT sintomatico do IAM inferior = atropina 0,5-1mg EV (ate 3mg) e marcapasso transcutaneo nas pas do desfibrilador ate transferir. Tenha amiodarona, adrenalina e atropina prontas. Glicemia capilar; corrija K+ e Mg se disponiveis (alvo K 4-4,5) para prevenir arritmia.",
    "SUPORTE CLINICO E QUEM NAO LISA: para com contraindicacao a trombolise, Killip III-IV ou supra persistente pos-lise, a conduta e estabilizar + transferir para ICP de resgate (sem balao na UPA, suporte e clinico). Nitrato SL/EV se PA permite, EVITANDO em IAM inferior/de VD com hipotensao e em uso de sildenafil/tadalafila. Morfina 2-4mg EV titulada apenas para dor refrataria (pode reduzir absorcao do antiagregante). Edema agudo de pulmao: VNI (CPAP/BiPAP) + nitrato EV + furosemida; intube se rebaixamento ou falencia da VNI. Cuidado: NAO faca expansao volemica agressiva as cegas em IAM anterior; em IAM de VD com hipotensao, faca volume cauteloso.",
    "TRANSFERENCIA/REGULACAO desde o inicio: contate a Central de Regulacao / Vaga Zero ASSIM QUE confirmar o supra (em paralelo a reperfusao, nao depois). Transfira em transporte avancado (USA/SAMU) monitorizado, com profissional habilitado, levando ECG impresso, horarios (dor/trombolise), drogas administradas e desfibrilador. Apos fibrinolise, a meta e ICP em 3-24h (rotina) ou imediata se sinais de FALHA da lise (dor persistente + supra que nao cai >=50% em 60-90min) - sinalize isso a regulacao. Documente tudo (medico-legal e continuidade no terciario).",
    "ECG SERIADO, NAO ESPERE TROPONINA: supra de ST em 2 derivacoes contiguas (ou BRE/BRD novo) JA fecha STEMI - reperfunda sem aguardar troponina nem 2a coleta. Se ECG duvidoso, repita a cada 10-15min e faca derivacoes direitas (V3R-V4R, p/ VD) e posteriores (V7-V9, p/ parede dorsal) - frequentemente omitidas e mudam a conduta (ex.: VD contraindica nitrato). A coleta de marcador NAO deve atrasar a reperfusao."
  ],
  "avc-isquemico": [
    "ABC + glicemia capilar JA: hipoglicemia < 60 mimetiza AVC — corrija com glicose 50% IV (40–60 mL = 4–6 amp de 10 mL) + tiamina 100 mg IV antes da glicose no etilista/desnutrido. O2 so se SatO2 < 94%. Cabeceira 0–30°, decubito lateral se vomito/rebaixamento, ZERO via oral (jejum) ate teste de degluticao — risco de broncoaspiracao.",
    "Cronometro: anote a HORA DE INICIO (ou ultima vez visto bem) — e o dado que decide trombolise. Aplique escala (Cincinnati se nao dominar o NIHSS) e ACIONE A REGULACAO/SAMU IMEDIATAMENTE: AVC e tempo-dependente e o papel da UPA e ESTABILIZAR e TRANSFERIR rapido para centro com TC e trombolise — nao tratar definitivamente aqui.",
    "Hipertensao permissiva: NAO baixe a PA de rotina. Sem TC para excluir hemorragia, so trate se PA > 220x120 (ou emergencia hipertensiva associada: EAP, disseccao, IAM). Use o que ha na REMUME — captopril 25 mg VO/SL (se degluticao segura) — e reduza no MAXIMO ~15% em 24 h. Queda abrupta piora a penumbra. Evite nifedipino sublingual (queda descontrolada). Se houver chance de trombolise no destino, o alvo passa a < 185/110 — alinhe com a regulacao.",
    "NAO de AAS nem qualquer antiagregante/anticoagulante na UPA sem TC excluindo hemorragia: antiagregar AVC hemorragico e catastrofico. AAS 200–300 mg e decisao do centro de referencia APOS a TC e confirmacao de degluticao segura. Na duvida, priorize a transferencia em vez de medicar.",
    "Trate o que mata e o que confunde enquanto espera vaga: convulsao com diazepam 10 mg IV lento; febre com dipirona (febre piora desfecho); SF 0,9% para hidratar (NUNCA soro glicosado/hipotonico — pioram o edema), mantendo normoglicemia. Monitor, acesso venoso calibroso e ECG 12 derivacoes (FA e causa frequente).",
    "Transfira MONITORIZADO, com acompanhamento medico/enfermagem e folha de regulacao trazendo horario de inicio, escala/NIHSS, glicemia, PA seriada e medicacoes feitas. Reavalie a via aerea ANTES de embarcar: Glasgow caindo ou ≤ 8 = considerar IOT antes do transporte. Paciente que dessatura ou broncoaspira na ambulancia perde a janela."
  ],
  "anafilaxia": [
    "ADRENALINA IM JA, sem esperar acesso venoso: 0,5 mg na coxa (vasto lateral) no adulto = 0,5 mL de adrenalina 1 mg/mL (1:1000); crianca 0,01 mg/kg (max 0,3 mg ate ~25-30 kg, 0,5 mg acima). Repita a cada 5-15 min se persistir hipotensao/dispneia/edema. NAO use anti-H1 nem corticoide como 1a linha - so a adrenalina reverte o quadro. A ampola de adrenalina 1 mg/mL esta no carrinho de parada de qualquer UPA: e a droga que salva.",
    "Deite o paciente e eleve as pernas (decubito dorsal com membros inferiores elevados - NAO Trendelenburg cefalo-declive, que piora a ventilacao). NUNCA sente nem levante o paciente subitamente (risco de PCR por sindrome do ventriculo vazio). O2 alto fluxo em mascara nao-reinalante 10-15 L/min. Se hipotensao: cristaloide em bolus rapido aberto - SF 0,9% ou Ringer lactato 1-2 L no adulto (20 mL/kg na crianca), repetindo conforme resposta; a hipovolemia relativa por extravasamento e o motor do choque.",
    "Refrataria (sem melhora apos 2-3 doses IM): inicie adrenalina EV em infusao continua TITULADA, idealmente em bomba (0,05-0,2 mcg/kg/min) com monitor cardiaco e PA frequente. Sem bomba na UPA: diluicao segura para microgotas e 1 mg em 100 mL de SF (= 10 mcg/mL) correndo em equipo de microgotas e titulada pela PA/perfusao - evite a diluicao ultra-dilu ida de 1 mcg/mL, que exige volumes enormes e atrasa a resposta. Se NAO houver monitor nem bomba, mantenha adrenalina IM repetida; NUNCA faca bolus EV de adrenalina nao diluida (risco de arritmia grave/IAM/AVC).",
    "Adjuvantes (nunca substituem a adrenalina, so complementam apos ela): broncoespasmo/sibilancia persistente - nebulizacao com salbutamol ou fenoterol (REMUME), repetir conforme necessidade; urticaria/prurido residual - anti-H1 (prometazina IM, da UPA); corticoide para reduzir reacao bifasica - hidrocortisona 200 mg EV (ou metilprednisolona 1-2 mg/kg EV se houver). Paciente em uso de betabloqueador e refratario a adrenalina: glucagon 1-5 mg EV lento, se disponivel na unidade.",
    "Acione a REGULACAO/SAMU para vaga em hospital com UTI ASSIM QUE der a 1a adrenalina - regule cedo, nao espere estabilizar. Mantenha observacao monitorada por no minimo 6-12 h (estenda ate 24 h se reacao grave, hipotensao, asmatico, ou necessidade de >1 dose de adrenalina) pelo risco de reacao bifasica. Transfira sempre acompanhado, com acesso venoso, O2, monitor e a ampola de adrenalina a beira do leito - nunca libere para transporte sem essas condicoes.",
    "VIA AEREA e prioridade absoluta: ao primeiro sinal de edema de glote, estridor, rouquidao progressiva ou disfagia, chame ajuda e prepare IOT PRECOCE (intube antes do edema fechar a via), com o medico mais experiente e o tubo de menor calibre disponivel; tenha plano de falha de via aerea pronto (cricotireoidostomia / dispositivo supraglotico). Alta SO apos periodo de observacao sem recidiva, com receita de prednisona + anti-H1 VO por alguns dias, orientacao escrita de retorno imediato se recorrencia, identificacao e suspensao do gatilho, e encaminhamento para adrenalina autoinjetavel/alergista quando indicado."
  ],
  "eme": [
    "BENZODIAZEPINICO QUE EXISTE NA UPA (1a linha, doses cheias - subdose e o erro mais comum): glicemia capilar JA + monitor/oximetria antes de tudo. Diazepam 10mg EV lento (0,15-0,2mg/kg, max 10mg/dose), pode repetir 1x apos 5 min (dose total ate ~20-30mg) - diazepam EV recidiva rapido (redistribui em ~20min), por isso a 2a linha entra LOGO em seguida, nao depois. SEM veia: Midazolam 10mg IM (5mg se 13-40kg) na coxa/deltoide - IM funciona e dispensa acesso. Tiamina 100-300mg EV ANTES de glicose; glicose 50% 40-50ml so se hipoglicemia. Gestante/puerpera = pense ECLAMPSIA: Sulfato de Magnesio 4-6g EV em 15-20min + manter infusao.",
    "ABC PRIMEIRO E SIMULTANEO (o que mais mata na UPA e a apneia pos-benzo, nao a crise): O2 alto fluxo em mascara, aspiracao pronta, lateralizacao, cabeceira protegida. Dois acessos venosos (antiepilepticos correm separados do benzo). Monitor + oximetria + PA + capnografia se houver. Material de via aerea ABERTO ao lado: laringoscopio testado, tubos, AMBU conectado ao O2, bougie, drogas de inducao ja aspiradas. Tenha vasopressor a mao (a 2a linha e a inducao causam hipotensao). Cheque temperatura: hipertermia mantida na crise e emergencia, resfrie.",
    "2a LINHA com o que ha na REMUME, em PARALELO a 1a (nao espere o benzo falhar para preparar): Fenitoina 20mg/kg EV (max ~1,5g) diluida SO em SF 0,9% (precipita em SG), infusao LENTA <=50mg/min (idoso/cardiopata <=20-25mg/min) em bomba ou gotejo controlado, com ECG/PA continuos - se hipotensao/bradiarritmia, reduza a velocidade ou pause. Se a UPA dispoe de Levetiracetam 60mg/kg EV (max 4,5g), prefira: igual eficacia, sem precipitacao, sem monitorizacao cardiaca obrigatoria - escolha em idoso/cardiopata/hipotenso. Acido valproico 40mg/kg EV e alternativa se disponivel (evitar em gestante e hepatopata). ACIONE REGULACAO/SAMU AGORA, em paralelo - vaga de CTI demora.",
    "MAL EPILEPTICO REFRATARIO (manteve crise apos benzo + 2a linha) = VIA AEREA DEFINITIVA + SEDACAO CONTINUA, nao mais bolus de benzo (so somam apneia sem controlar). Faca sequencia rapida de intubacao com o que existe: inducao com Quetamina OU Etomidato OU Midazolam (evite tiopental/propofol se hipotenso ou sem bomba/monitor adequado) + bloqueador (succinilcolina ou rocuronio - lembre que o bloqueador mascara a crise motora, mantenha a sedacao titulada por baixo). Apos intubar, Midazolam em infusao continua (bolus 0,2mg/kg + 0,05-0,4mg/kg/h titulado) como ponte. Isto e medida de estabilizacao para transporte: o tratamento definitivo (EEG, anestesico) e no terciario - a transferencia ja deve estar em curso.",
    "PROCURE A CAUSA EM PARALELO (muda a conduta e e facil esquecer na correria): glicemia (feita), Na/Ca/eletrolitos se houver laboratorio, gestacao/eclampsia, febre + sinais meningeos (se suspeita de neuroinfeccao, Ceftriaxona 2g EV empirica JA - nao espere TC/puncao, que a UPA nao tem; some Aciclovir se suspeita de encefalite), intoxicacao/abstinencia alcoolica (tiamina ANTES da glicose), TCE/AVC, uremia. Crise focal ou que nao cede a tratamento adequado = bandeira vermelha para lesao estrutural = neuroimagem URGENTE no terciario.",
    "ESTABILIZAR PARA TRANSFERIR (o desfecho real da UPA e remover o paciente com seguranca): so transporte apos crise controlada, via aerea protegida (intubado se rebaixado/refratario), hemodinamica estavel, monitorizado, com bomba e sedacao garantidas e ACOMPANHAMENTO MEDICO no transporte (mal refratario = transporte medicalizado, nao apenas SAMU basico). Leve: benzo extra, dose de resgate do antiepiletico, drogas de inducao, AMBU e material de reintubacao, vasopressor. Documente horarios, doses e resposta para o terciario. Contato com a regulacao deve ter comecado na 1a/2a linha."
  ],
  "hipercalemia": [
    "ESTABILIZE A MEMBRANA JA (nao espere o K do lab): se ECG alterado (T apiculada, QRS alargado, onda sinusoidal, bradi/BAV) OU K conhecido >6,5 -> Gluconato de calcio 10% 10-20 mL IV lento em 5-10 min sob monitor cardiaco; repita em 5-10 min se o ECG nao melhorar. Sem gluconato? Cloreto de calcio 10% 10 mL (tem ~3x mais calcio elementar) SO em acesso central/calibroso com bom retorno (extravasou = necrose). Efeito dura ~30-60 min: e PONTE, nao trata o K. Em digital franco evite o calcio salvo arritmia ameacadora.",
    "DESLOQUE O K PRA DENTRO DA CELULA: Insulina regular 10 UI IV + Glicose 50% 100 mL (50 g) IV; mantenha SG10% correndo e CHEQUE glicemia capilar aos 30-60 min E mantenha controles ate 3-6h (hipoglicemia tardia e a complicacao mais comum). Se ja hiperglicemico (>250), faca a insulina SEM glicose. Beta-2 que toda UPA tem: Salbutamol nebulizacao 10-20 gotas (5x a dose de asma) ou 4-8 puffs; cautela em coronariopata/taquiarritmico. NaHCO3 8,4% so se acidose metabolica documentada e NUNCA na mesma via do calcio (precipita).",
    "REMOVA o K e CORTE o que sobe: suspenda IECA/BRA/espironolactona/AINE/suplemento de K/heparina e revise dieta e SF com KCl. Furosemida 40-80 mg IV SE o paciente urina e nao esta hipovolemico/anurico -> reponha volume com SF 0,9% antes/junto se desidratado. Resina (poliestirenossulfonato/Sorcal) age em HORAS, e adjuvante e NAO conta como tratamento agudo: nao adie a transferencia esperando resina; evite em ileo/obstrucao/pos-op abdominal.",
    "ACIONE A REGULACAO EM PARALELO, NAO DEPOIS: K >6,5, qualquer alteracao de ECG, ou anuria/IRA/intoxicacao = precisa de VAGA DE DIALISE -> ligue pra Central de Regulacao/SAMU JA enquanto trata. A estabilizacao na UPA e ponte de horas, nao tratamento definitivo do anurico/dialitico. Transporte com monitor cardiaco, acesso garantido, ampola de gluconato de calcio na mochila e SG10% correndo; medico/enfermeiro acompanhando se ECG alterado.",
    "REPITA O ECG E REAVALIE: o ECG e seu 'potassio em tempo real' quando o lab demora ou nao tem -> piora de QRS/sinusoidal = mais calcio AGORA. Em PCR por hipercalemia (AESP/FV com QRS largo): RCP + Gluconato/Cloreto de calcio IV + bicarbonato, mantendo as medidas de deslocamento. Lembre que insulina e beta-2 SO 'escondem' o K e ele REBOTA em ~2-4h se a remocao/dialise nao acontecer -> reavalie K de controle (se houver) e o ECG.",
    "CUIDADO COM PSEUDOHIPERCALEMIA E ARMADILHAS: hemolise da coleta/garrote demorado/punho cerrado da K falso alto SEM alteracao de ECG -> se clinica e ECG normais, RECOLHA antes de tratar agressivo. Na duvida COM ECG alterado, trate. Nao trate 'so o numero': correlacione sempre numero + ECG + clinica (oliguria, drogas, IRA)."
  ],
  "intoxicacoes": [
    "SUPORTE > ANTIDOTO (a base que SEMPRE tem na UPA): a maioria das intoxicacoes se resolve com ABCDE + tempo, nao com antidoto. Garanta via aerea (IOT precoce se Glasgow <=8 ou broncoaspiracao), O2, 2 acessos, SF 0,9% para hipotensao, monitor + ECG seriado (olhar QRS e QT) e GLICEMIA CAPILAR em TODO rebaixado. Convulsao por toxico: diazepam/midazolam (NUNCA fenitoina - ineficaz/agrava em toxico). Agitacao/abstinencia/sindrome adrenergica (cocaina, simpaticomimetico): benzodiazepinico em titulacao, NAO betabloqueador isolado.",
    "DESCONTAMINACAO realista de UPA: carvao ativado 1 g/kg VO ou SNG SE via aerea protegida e ingesta recente (<1-2h) de dose toxica - NAO usar em alcoois, litio, ferro, hidrocarboneto, caustico ou metais, e NAO usar se rebaixado sem IOT (risco de broncoaspiracao). Carvao em DOSES REPETIDAS (a cada 4-6h) tem beneficio real e baixo custo em carbamazepina, fenobarbital, teofilina, dapsona e quinina. Esqueca lavagem gastrica de rotina (so cogitar <1h, droga letal, via aerea segura). Caustico/hidrocarboneto: NAO induzir vomito, NAO sonda as cegas, NAO carvao - so suporte e regular.",
    "ANTIDOTO QUE FALTA, IMPROVISO SEGURO COM REMUME: (1) Sem NAC para paracetamol - hidrate, colha funcao hepatica/TAP-INR e regule/TRANSFIRA CEDO (NAC e tempo-dependente, ideal <8h; nivel serico orienta mas raramente disponivel na UPA). (2) Sem flumazenil - trate BZD so com suporte/via aerea (flumazenil pode convulsionar e e perigoso). (3) Sem glucagon para betabloqueador/BCC - use SF + noradrenalina/dopamina, atropina na bradicardia, e gluconato de calcio 10% (tem na UPA) nos bloqueadores de canal de calcio; se refratario e equipe treinada, insulina regular alta dose + glicose (drogas que existem no REMUME) COM monitorizacao rigorosa de glicemia e potassio. (4) Anticolinergico/organofosforado: atropina IV em doses dobradas a cada 3-5 min ate atropinizar (secrecao traqueal seca, ausculta limpa) - atropina existe no carrinho.",
    "TOXICO COM RECURSO DISPONIVEL NA PAREDE: bicarbonato de sodio 8,4% (tem na UPA) e o coringa - use em QRS alargado (>100-120 ms) por triciclico/antiarritmico (bolus 1-2 mEq/kg ate estreitar QRS, mirar pH 7,45-7,55) e na alcalinizacao urinaria de salicilato/fenobarbital. Opioide: naloxona costuma existir (titular para recuperar VENTILACAO, nao consciencia plena, em dependente) - se faltar, o tratamento e VENTILAR (bolsa-valva-mascara / IOT), que salva enquanto regula. Hipoglicemia por hipoglicemiante: glicose 50% IV + glicose continua 10%; nas SULFONILUREIAS observar/internar pela hipoglicemia tardia e recorrente (nao dar alta apos correcao unica).",
    "QUANDO ESTABILIZAR E ACIONAR REGULACAO/CIATox: ligue CEDO - SAMU 192 (sempre disponivel, conecta ao Centro de Informacao Toxicologica regional) ou o disque-intoxicacao nacional 0800 722 6001; orientacao 24h muda conduta/doses. Regule/transfira para terciario se: antidoto especifico indisponivel e necessario (NAC, fomepizol/etanol em metanol-etilenoglicol, antiveneno/soro especifico, indicacao de dialise), QRS/QT alargando, acidose metabolica refrataria, choque ou rebaixamento que exige UTI. Transfira SEMPRE estabilizado: via aerea definida, acesso, droga vasoativa correndo se preciso, monitor, e leve amostra/embalagem do agente e horario da ingesta.",
    "ARMADILHAS QUE MATAM NA UPA (evitar improviso perigoso): nao dar carvao em paciente sonolento sem IOT; nao usar flumazenil em quem pode ter co-ingestao de triciclico ou ser dependente de BZD; em organofosforado, EPI/descontaminacao da pele para proteger a equipe e atropinizar ANTES de pralidoxima; nao induzir emese nunca; nao usar betabloqueador isolado em intoxicacao por cocaina/simpaticomimetico; e VIGIAR toxicos de efeito tardio (paracetamol, sulfonilureia, formulacoes de liberacao prolongada, metanol/etilenoglicol) - paciente 'bem' agora pode descompensar, entao observe/regule em vez de dar alta precoce."
  ]
};
